name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Build and Test C# Code
      run: |
        dotnet build
        dotnet test

    - name: Build, Lint and Test TypeScript Code
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build
        npm run lint
        npm t

    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
        webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}